export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const GET_CAR_BEGIN = "GET_CAR_BEGIN";
export const GET_CAR_SUCCESS = "GET_CAR_SUCCESS";
export const GET_CAR_ERROR = "GET_CAR_ERROR"
export const GET_JOB_ERROR = "GET_JOB_ERROR";

export const SET_RENT_CAR = "SET_RENT_CAR";
export const SET_DIF_DAY = "SET_DIF_DAY";

export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";

export const GET_ORDER_BEGIN = "GET_ORDER_BEGIN";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const MAKE_ORDER_BEGIN = "MAKE_ORDER_BEGIN";
export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_ERROR = "MAKE_ORDER_ERROR";

export const GET_USER_ORDER_BEGIN = "GET_USER_ORDER_BEGIN";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_ERROR = "GET_USER_ORDER_ERROR";

export const CLEAR_CAR_SELECTED = "CLEAR_CAR_SELECTED";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const SEND_REFRESH_BEGIN = "SEND_REFRESH_BEGIN";
export const SEND_REFRESH_SUCCESS = "SEND_REFRESH_SUCCESS";

export const EMPTY_PERSON_ID = "EMPTY_PERSON_ID";

export const CHANGE_PROFILE_BEGIN = "CHANGE_PROFILE_BEGIN";
export const CHANGE_PROFILE_ERROR = "CHANGE_PROFILE_ERROR";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";

export const DELETE_ORDER_BEGIN = "DELETE_ORDER_BEGIN"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"

export const INSERT_CAR_BEGIN = "INSERT_CAR_BEGIN"
export const INSERT_CAR_SUCCESS = "INSERT_CAR_SUCCESS"
export const INSERT_CAR_ERROR = "INSERT_CAR_ERROR"

export const DELETE_CAR_BEGIN = "DELETE_CAR_BEGIN"
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS"
export const DELETE_CAR_ERROR = "DELETE_CAR_ERROR"

export const SET_CAR_SELECTED = "SET_CAR_SELECTED"
export const CANCEL_CAR_EDIT = "CANCEL_CAR_EDIT"

export const UPDATE_CAR_BEGIN = "UPDATE_CAR_BEGIN"
export const UPDATE_CAR_SUCCESS  = "UPDATE_CAR_SUCCESS"
export const UPDATE_CAR_ERROR = "UPDATE_CAR_ERROR"

export const APPROVING_ORDER_BEGIN = "APPROVING_ORDER_BEGIN"
export const APPROVING_ORDER_SUCCESS = "APPROVING_ORDER_SUCCESS"
export const APPROVING_ORDER_ERROR = "APPROVING_ORDER_ERROR"

export const SET_FILTERED_ORDER = "SET_FILTERED_ORDEr"